---
name: Python Tests
on:
  push:
    branches:
      - main
    paths:
      - src/cost_export/**
      - .github/workflows/python-tests.yml
  pull_request:
    branches:
      - main
    paths:
      - src/cost_export/**
      - .github/workflows/python-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Cost Export Unit Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"

      - name: Run unit tests
        run: python -m unittest discover -s src/cost_export/test -v
