---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  debug-terraform-docs:
    runs-on: ubuntu-latest
    name: Debug Terraform Docs Diff
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1.4.1
        with:
          working-dir: .
          fail-on-diff: false
      - run: git diff

  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@main
    name: Module Validation
    with:
      working-directory: .
      enable-commitlint: false
